# Generated by Django 5.2.15 on 2026-07-07 02:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=160)),
                ('difficulty', models.CharField(max_length=20)),
                ('summary', models.TextField()),
                ('key_takeaways', models.JSONField(blank=True, default=list)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['module__sort_order', 'sort_order', 'card_id'],
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_id', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'path_id'],
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('icon', models.CharField(blank=True, max_length=40)),
                ('color', models.CharField(default='#40a0f0', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'key'],
            },
        ),
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concept_id', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(max_length=40)),
                ('difficulty', models.CharField(max_length=20)),
                ('explanation', models.TextField()),
                ('related', models.ManyToManyField(blank=True, to='learning.concept')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('content', models.TextField()),
                ('code_example', models.TextField(blank=True)),
                ('visual_type', models.CharField(blank=True, max_length=40)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='learning.knowledgecard')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.knowledgecard')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.learningpath')),
            ],
            options={
                'ordering': ['sort_order'],
                'unique_together': {('path', 'card')},
            },
        ),
        migrations.AddField(
            model_name='learningpath',
            name='cards',
            field=models.ManyToManyField(related_name='learning_paths', through='learning.LearningPathCard', to='learning.knowledgecard'),
        ),
        migrations.AddField(
            model_name='knowledgecard',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='learning.module'),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_id', models.SlugField(max_length=80, unique=True)),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct', models.PositiveIntegerField(default=0)),
                ('explanation', models.TextField()),
                ('concepts', models.ManyToManyField(blank=True, related_name='quiz_questions', to='learning.concept')),
            ],
            options={
                'ordering': ['quiz_id'],
            },
        ),
    ]
